Localization = {
    language = "EN",
    languages = {
        ["EN"] = {
            ["ACCEPT"] = "Accept",
            ["ACCEPTED_OFFER_AND_REMOVED_OTHER_OFFERS"] = "Accepted the offer, removed other offers, and returned deposits.",
            ["ADD_IMAGE"] = "Add Image",
            ["ADD_MID_POINT"] = "Add Mid Point",
            ["ADD_POINT"] = "Add Point",
            ["APARTMENT"] = "Apartment",
            ["APARTMENTS"] = "Apartments",
            ["ASKING_PRICE"] = "Asking price",
            ["BREAK_IN"] = "Break In",
            ["BUILDING"] = "Building",
            ["BUY"] = "Buy",
            ["BUY_STORAGE"] = "Buy Storage",
            ["CAMERA"] = "Camera",
            ["CANCEL"] = "Cancel",
            ["CANT_SAVE_NOW"] = "You can't save right now",
            ["CHANGE_PRICE"] = "Change Price",
            ["CLOSE"] = "Close",
            ["DECORATE"] = "Decorate",
            ["DELETING_STORAGE"] = "Are you sure you want to remove this storage?",
            ["DELETING_STORAGE_SECOND"] = "Are you REALLY sure you want to remove this storage???",
            ["DELETE_FURNITURE"] = "Remove Furniture",
            ["DOOR"] = "Door",
            ["DOORBELL"] = "The doorbell rings",
            ["DOORLOCK"] = "Lock status changed",
            ["ENTER"] = "Enter",
            ["ENTER_APARTMENT"] = "Enter Apartment",
            ["ENTER_GARAGE"] = "Enter Garage",
            ["ENTER_NAME"] = "Enter name",
            ["ENTER_OFFER"] = "Enter offer amount",
            ["ENTER_PHONE_NUMBER"] = "Enter phone number",
            ["ENTER_PRICE"] = "Enter Price",
            ["ENTER_URL"] = "Enter URL",
            ["EXIT_APARTMENT"] = "Exit Apartment",
            ["EXIT_GARAGE"] = "Exit Garage",
            ["GARAGE"] = "Garage",
            ["GIVE_PERMISSIONS"] = "Give Permissions",
            ["GPS"] = "Gps",
            ["IMAGE_URL"] = "Image URL",
            ["LIST"] = "List",
            ["LOCK"] = "Lock",
            ["LOCK_DOOR"] = "Lock Door",
            ["MAKE_OFFER"] = "Make Offer",
            ["MANAGE_PERMISSIONS"] = "Manage Permissions",
            ["MODIFY_FURNITURE"] = "Modify Furniture",
            ["MONEY_SYMBOL"] = "$",
            ["MOVE_POINT"] = "Move Point",
            ["MOVE_STORAGE"] = "Move Storage",
            ["MY_OFFERS"] = "My Offers",
            ["MY_PROPERTIES"] = "My Properties",
            ["NAME"] = "Name",
            ["NEW"] = "New",
            ["OFFERS"] = "Offers",
            ["OFFER_INFO"] = [[
                By sending this offer, the specified amount will be deducted from your bank account. 
                If the offer is accepted, you will receive the property. 
                If the offer is rejected or canceled, the money will be refunded. You can cancel your offer at any time.
            ]],
            ["OK"] = "OK",
            ["OPEN_APARTMENTS_MENU"] = "Open Apartments Menu",
            ["OPEN_STORAGE"] = "Open Storage",
            ["OWNER"] = "Owner",
            ["PERMISSIONS"] = "Permissions",
            ["PRICE"] = "Price",
            ["PROPERTY_MENU"] = "Property Menu",
            ["REMOVE_FURNITURE"] = "Remove Furniture",
            ["REMOVE_IMAGE"] = "Remove Image",
            ["REMOVE_PERMISSION"] = "Remove permissions",
            ["REMOVE_POINT"] = "Remove Point",
            ["REMOVE_STORAGE"] = "Remove Storage",
            ["REMOVED_OFFER_AND_RETURNED_MONEY"] = "Removed the offer and returned deposit.",
            ["RESIDENT"] = "Resident",
            ["RING_BELL"] = "Ring Bell",
            ["SAVE"] = "Save",
            ["SECONDS"] = "Seconds",
            ["SECONDARY_OWNER"] = "Secondary owner",
            ["SELECT_LOCATION"] = "Select Location",
            ["SELECT_PLAYER"] = "Select player",
            ["SELECT_SHELL"] = "Select Shell",
            ["SEND_OFFER"] = "Send offer",
            ["SET_DOOR"] = "Set Door",
            ["SET_EXTERIOR"] = "Set Exterior",
            ["SET_GARAGE"] = "Set Garage",
            ["SLOTS"] = "Slots",
            ["STORAGES"] = "Storages",
            ["UNLISTED"] = "Unlisted",
            ["UNLOCK"] = "Unlock",
            ["UNLOCK_DOOR"] = "Unlock Door",
            ["UNLOCK_FOR"] = "Unlock For",
            ["WARDROBE"] = "Wardrobe",
            ["YOU_OWN_MAX_PROPERTIES"] = "You own max amount of properties",

            ["DOOR_OFFSET"] = "Door offset",
            ["Z_OFFSET_DOWN"] = "-Z Offset",
            ["Z_OFFSET_UP"] = "+Z Offset",
        },        
        ["FI"] = {
            ["ACCEPT"] = "Hyväksy",
            ["ACCEPTED_OFFER_AND_REMOVED_OTHER_OFFERS"] = "Tarjous hyväksytty, muut tarjoukset poistettu ja talletukset palautettu.",
            ["ADD_IMAGE"] = "Lisää kuva",
            ["ADD_MID_POINT"] = "Lisää välietappi",
            ["ADD_POINT"] = "Lisää piste",
            ["APARTMENT"] = "Asunto",
            ["APARTMENTS"] = "Asunnot",
            ["ASKING_PRICE"] = "Pyyntihinta",
            ["BREAK_IN"] = "Murtaudu sisään",
            ["BUILDING"] = "Rakennus",
            ["BUY"] = "Osta",
            ["BUY_STORAGE"] = "Osta säilytystila",
            ["CAMERA"] = "Kamera",
            ["CANCEL"] = "Peruuta",
            ["CANT_SAVE_NOW"] = "Et voi tallentaa nyt",
            ["CHANGE_PRICE"] = "Muuta hintaa",
            ["CLOSE"] = "Sulje",
            ["DECORATE"] = "Sisusta",
            ["DELETING_STORAGE"] = "Oletko varma, että haluat poistaa tämän säilytystilan?",
            ["DELETING_STORAGE_SECOND"] = "OLETKO IHAN VARMA, että haluat poistaa tämän säilytystilan???",
            ["DELETE_FURNITURE"] = "Poista huonekalu",
            ["DOOR"] = "Ovi",
            ["DOORBELL"] = "Ovikello soi",
            ["DOORLOCK"] = "Lukituksen tila muuttui",
            ["ENTER"] = "Syötä",
            ["ENTER_APARTMENT"] = "Mene asuntoon",
            ["ENTER_GARAGE"] = "Mene autotalliin",
            ["ENTER_NAME"] = "Syötä nimi",
            ["ENTER_OFFER"] = "Syötä tarjousmäärä",
            ["ENTER_PHONE_NUMBER"] = "Syötä puhelinnumero",
            ["ENTER_PRICE"] = "Syötä hinta",
            ["ENTER_URL"] = "Syötä URL",
            ["EXIT_APARTMENT"] = "Poistu asunnosta",
            ["EXIT_GARAGE"] = "Poistu autotallista",
            ["GARAGE"] = "Autotalli",
            ["GIVE_PERMISSIONS"] = "Anna oikeudet",
            ["GPS"] = "GPS",
            ["IMAGE_URL"] = "Kuvan URL",
            ["LIST"] = "Lista",
            ["LOCK"] = "Lukitse",
            ["LOCK_DOOR"] = "Lukitse ovi",
            ["MAKE_OFFER"] = "Tee tarjous",
            ["MANAGE_PERMISSIONS"] = "Hallitse oikeuksia",
            ["MODIFY_FURNITURE"] = "Muokkaa huonekaluja",
            ["MONEY_SYMBOL"] = "€",
            ["MOVE_POINT"] = "Siirrä pistettä",
            ["MOVE_STORAGE"] = "Siirrä säilytystila",
            ["MY_OFFERS"] = "Omat tarjoukset",
            ["MY_PROPERTIES"] = "Omat asunnot",
            ["NAME"] = "Nimi",
            ["NEW"] = "Uusi",
            ["OFFERS"] = "Tarjoukset",
            ["OFFER_INFO"] = [[
                Lähettämällä tämän tarjouksen määritetty summa vähennetään pankkitililtäsi.
                Jos tarjous hyväksytään, saat asunnon.
                Jos tarjous hylätään tai peruutetaan, rahat palautetaan. Voit peruuttaa tarjouksen milloin tahansa.
            ]],
            ["OK"] = "OK",
            ["OPEN_APARTMENTS_MENU"] = "Avaa asuntojen valikko",
            ["OPEN_STORAGE"] = "Avaa säilytystila",
            ["OWNER"] = "Omistaja",
            ["PERMISSIONS"] = "Oikeudet",
            ["PRICE"] = "Hinta",
            ["PROPERTY_MENU"] = "Asuntojen valikko",
            ["REMOVE_FURNITURE"] = "Poista huonekalu",
            ["REMOVE_IMAGE"] = "Poista kuva",
            ["REMOVE_PERMISSION"] = "Poista oikeudet",
            ["REMOVE_POINT"] = "Poista piste",
            ["REMOVE_STORAGE"] = "Poista säilytystila",
            ["REMOVED_OFFER_AND_RETURNED_MONEY"] = "Tarjous poistettu ja talletus palautettu.",
            ["RESIDENT"] = "Asukas",
            ["RING_BELL"] = "Soita ovikelloa",
            ["SAVE"] = "Tallenna",
            ["SECONDS"] = "Sekunnit",
            ["SECONDARY_OWNER"] = "Toissijainen omistaja",
            ["SELECT_LOCATION"] = "Valitse sijainti",
            ["SELECT_PLAYER"] = "Valitse pelaaja",
            ["SELECT_SHELL"] = "Valitse malli",
            ["SEND_OFFER"] = "Lähetä tarjous",
            ["SET_DOOR"] = "Aseta ovi",
            ["SET_EXTERIOR"] = "Aseta ulkoasu",
            ["SET_GARAGE"] = "Aseta autotalli",
            ["SLOTS"] = "Paikat",
            ["STORAGES"] = "Säilytystilat",
            ["UNLISTED"] = "Listasta poistettu",
            ["UNLOCK"] = "Avaa",
            ["UNLOCK_DOOR"] = "Avaa ovi",
            ["UNLOCK_FOR"] = "Avaa henkilölle",
            ["WARDROBE"] = "Vaatekaappi",
            ["YOU_OWN_MAX_PROPERTIES"] = "Omistat jo maksimimäärän asuntoja",

            ["DOOR_OFFSET"] = "Oven offset",
            ["Z_OFFSET_DOWN"] = "-Z Offset",
            ["Z_OFFSET_UP"] = "+Z Offset",
        },        
    },
}


local missingLocales = {}

function GetLocale(locale)
    if Localization.languages[Localization.language] and Localization.languages[Localization.language][locale] then
        return Localization.languages[Localization.language][locale]
    else
        missingLocales[locale] = true
        return locale
    end
end


function AddMissingLocale(locale)
    missingLocales[locale] = true
end

function PrintMissingLocales()
    for k, v in pairs(missingLocales) do
        print(string.format('["%s"] = ""', k))
    end
end
